pages = [{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/little/json.html","n":"little.json","t":"package little.json","d":"little/json"},
{"l":"api/little/json/Implicits$.html","n":"Implicits","t":"object Implicits","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$.html","n":"\\","t":"def \\(name: String): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$.html","n":"\\","t":"def \\(index: Int): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$.html","n":"\\\\","t":"def \\\\(name: String): Seq[JsonValue]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonValue$.html","n":"jsonValueToJsonValue","t":"given jsonValueToJsonValue: JsonInput[JsonValue]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonValue$.html","n":"apply","t":"def apply(value: JsonValue): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonObject$.html","n":"jsonValueToJsonObject","t":"given jsonValueToJsonObject: JsonInput[JsonObject]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonObject$.html","n":"apply","t":"def apply(value: JsonValue): JsonObject","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonArray$.html","n":"jsonValueToJsonArray","t":"given jsonValueToJsonArray: JsonInput[JsonArray]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonArray$.html","n":"apply","t":"def apply(value: JsonValue): JsonArray","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonString$.html","n":"jsonValueToJsonString","t":"given jsonValueToJsonString: JsonInput[JsonString]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonString$.html","n":"apply","t":"def apply(value: JsonValue): JsonString","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNumber$.html","n":"jsonValueToJsonNumber","t":"given jsonValueToJsonNumber: JsonInput[JsonNumber]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNumber$.html","n":"apply","t":"def apply(value: JsonValue): JsonNumber","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonBoolean$.html","n":"jsonValueToJsonBoolean","t":"given jsonValueToJsonBoolean: JsonInput[JsonBoolean]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonBoolean$.html","n":"apply","t":"def apply(value: JsonValue): JsonBoolean","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNull$.html","n":"jsonValueToJsonNull","t":"given jsonValueToJsonNull: JsonInput[JsonNull]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNull$.html","n":"apply","t":"def apply(value: JsonValue): JsonNull","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonStringToString$.html","n":"jsonStringToString","t":"given jsonStringToString: JsonInput[String]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonStringToString$.html","n":"apply","t":"def apply(value: JsonValue): String","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToShort$.html","n":"jsonNumberToShort","t":"given jsonNumberToShort: JsonInput[Short]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToShort$.html","n":"apply","t":"def apply(value: JsonValue): Short","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToInt$.html","n":"jsonNumberToInt","t":"given jsonNumberToInt: JsonInput[Int]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToInt$.html","n":"apply","t":"def apply(value: JsonValue): Int","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToLong$.html","n":"jsonNumberToLong","t":"given jsonNumberToLong: JsonInput[Long]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToLong$.html","n":"apply","t":"def apply(value: JsonValue): Long","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToFloat$.html","n":"jsonNumberToFloat","t":"given jsonNumberToFloat: JsonInput[Float]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToFloat$.html","n":"apply","t":"def apply(value: JsonValue): Float","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToDouble$.html","n":"jsonNumberToDouble","t":"given jsonNumberToDouble: JsonInput[Double]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToDouble$.html","n":"apply","t":"def apply(value: JsonValue): Double","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigInt$.html","n":"jsonNumberToBigInt","t":"given jsonNumberToBigInt: JsonInput[BigInt]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigInt$.html","n":"apply","t":"def apply(value: JsonValue): BigInt","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigDecimal$.html","n":"jsonNumberToBigDecimal","t":"given jsonNumberToBigDecimal: JsonInput[BigDecimal]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigDecimal$.html","n":"apply","t":"def apply(value: JsonValue): BigDecimal","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBoolean$.html","n":"jsonNumberToBoolean","t":"given jsonNumberToBoolean: JsonInput[Boolean]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonNumberToBoolean$.html","n":"apply","t":"def apply(value: JsonValue): Boolean","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"jsonValueToCollection","t":"given jsonValueToCollection[T, M[T]](using val convert: JsonInput[T])(using val factory: Factory[T, M[T]]): JsonInput[M[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"factory","t":"val factory: Factory[T, M[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"apply","t":"def apply(value: JsonValue): M[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"jsonValueToOption","t":"given jsonValueToOption[T](using val convert: JsonInput[T]): JsonInput[Option[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"apply","t":"def apply(value: JsonValue): Option[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"jsonValueToTry","t":"given jsonValueToTry[T](using val convert: JsonInput[T]): JsonInput[Try[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"apply","t":"def apply(value: JsonValue): Try[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"jsonValueToEither","t":"given jsonValueToEither[A, B](using val left: JsonInput[A])(using val right: JsonInput[B]): JsonInput[Either[A, B]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"left","t":"val left: JsonInput[A]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"right","t":"val right: JsonInput[B]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"apply","t":"def apply(value: JsonValue): Either[A, B]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$stringToJsonString$.html","n":"stringToJsonString","t":"given stringToJsonString: JsonOutput[String]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$stringToJsonString$.html","n":"apply","t":"def apply(value: String): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$shortToJsonNumber$.html","n":"shortToJsonNumber","t":"given shortToJsonNumber: JsonOutput[Short]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$shortToJsonNumber$.html","n":"apply","t":"def apply(value: Short): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$intToJsonNumber$.html","n":"intToJsonNumber","t":"given intToJsonNumber: JsonOutput[Int]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$intToJsonNumber$.html","n":"apply","t":"def apply(value: Int): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$longToJsonNumber$.html","n":"longToJsonNumber","t":"given longToJsonNumber: JsonOutput[Long]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$longToJsonNumber$.html","n":"apply","t":"def apply(value: Long): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$floatToJsonNumber$.html","n":"floatToJsonNumber","t":"given floatToJsonNumber: JsonOutput[Float]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$floatToJsonNumber$.html","n":"apply","t":"def apply(value: Float): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$doubleToJsonNumber$.html","n":"doubleToJsonNumber","t":"given doubleToJsonNumber: JsonOutput[Double]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$doubleToJsonNumber$.html","n":"apply","t":"def apply(value: Double): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$bigIntToJsonNumber$.html","n":"bigIntToJsonNumber","t":"given bigIntToJsonNumber: JsonOutput[BigInt]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$bigIntToJsonNumber$.html","n":"apply","t":"def apply(value: BigInt): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$bigDecimalToJsonNumber$.html","n":"bigDecimalToJsonNumber","t":"given bigDecimalToJsonNumber: JsonOutput[BigDecimal]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$bigDecimalToJsonNumber$.html","n":"apply","t":"def apply(value: BigDecimal): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$booleanToJsonBoolean$.html","n":"booleanToJsonBoolean","t":"given booleanToJsonBoolean: JsonOutput[Boolean]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$booleanToJsonBoolean$.html","n":"apply","t":"def apply(value: Boolean): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"arrayToJsonArray","t":"given arrayToJsonArray[T](using val convert: JsonOutput[T]): JsonOutput[Array[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"apply","t":"def apply(value: Array[T]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"iterableToJsonArray","t":"given iterableToJsonArray[T, M <: ([T] =>> Iterable[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"optionToJsonValue","t":"given optionToJsonValue[T, M <: ([T] =>> Option[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$noneToJsonValue$.html","n":"noneToJsonValue","t":"given noneToJsonValue: JsonOutput[None]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$noneToJsonValue$.html","n":"apply","t":"def apply(value: None): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"tryToJsonValue","t":"given tryToJsonValue[T, M <: ([T] =>> Try[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$failureToJsonValue$.html","n":"failureToJsonValue","t":"given failureToJsonValue: JsonOutput[Failure[_]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$failureToJsonValue$.html","n":"apply","t":"def apply(value: Failure[_]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"eitherToJsonValue","t":"given eitherToJsonValue[A, B, M <: ([A, B] =>> Either[A, B])](using val left: JsonOutput[A])(using val right: JsonOutput[B]): JsonOutput[M[A, B]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"left","t":"val left: JsonOutput[A]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"right","t":"val right: JsonOutput[B]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"apply","t":"def apply(value: M[A, B]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"rightToJsonValue","t":"given rightToJsonValue[T](using val convert: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"apply","t":"def apply(value: Right[_, T]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"leftToJsonValue","t":"given leftToJsonValue[T](using val convert: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"apply","t":"def apply(value: Left[T, _]): JsonValue","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"tupleToJsonField","t":"given tupleToJsonField[T](using val convert: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"apply","t":"def apply(value: (String, T)): (String, JsonValue)","d":"little/json/Implicits$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonValue$.html","n":"jsonValueToJsonValue","t":"given jsonValueToJsonValue: JsonInput[JsonValue]","d":"little/json/Implicits$$jsonValueToJsonValue$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonValue$.html","n":"apply","t":"def apply(value: JsonValue): JsonValue","d":"little/json/Implicits$$jsonValueToJsonValue$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonObject$.html","n":"jsonValueToJsonObject","t":"given jsonValueToJsonObject: JsonInput[JsonObject]","d":"little/json/Implicits$$jsonValueToJsonObject$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonObject$.html","n":"apply","t":"def apply(value: JsonValue): JsonObject","d":"little/json/Implicits$$jsonValueToJsonObject$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonArray$.html","n":"jsonValueToJsonArray","t":"given jsonValueToJsonArray: JsonInput[JsonArray]","d":"little/json/Implicits$$jsonValueToJsonArray$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonArray$.html","n":"apply","t":"def apply(value: JsonValue): JsonArray","d":"little/json/Implicits$$jsonValueToJsonArray$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonString$.html","n":"jsonValueToJsonString","t":"given jsonValueToJsonString: JsonInput[JsonString]","d":"little/json/Implicits$$jsonValueToJsonString$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonString$.html","n":"apply","t":"def apply(value: JsonValue): JsonString","d":"little/json/Implicits$$jsonValueToJsonString$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNumber$.html","n":"jsonValueToJsonNumber","t":"given jsonValueToJsonNumber: JsonInput[JsonNumber]","d":"little/json/Implicits$$jsonValueToJsonNumber$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNumber$.html","n":"apply","t":"def apply(value: JsonValue): JsonNumber","d":"little/json/Implicits$$jsonValueToJsonNumber$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonBoolean$.html","n":"jsonValueToJsonBoolean","t":"given jsonValueToJsonBoolean: JsonInput[JsonBoolean]","d":"little/json/Implicits$$jsonValueToJsonBoolean$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonBoolean$.html","n":"apply","t":"def apply(value: JsonValue): JsonBoolean","d":"little/json/Implicits$$jsonValueToJsonBoolean$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNull$.html","n":"jsonValueToJsonNull","t":"given jsonValueToJsonNull: JsonInput[JsonNull]","d":"little/json/Implicits$$jsonValueToJsonNull$"},
{"l":"api/little/json/Implicits$$jsonValueToJsonNull$.html","n":"apply","t":"def apply(value: JsonValue): JsonNull","d":"little/json/Implicits$$jsonValueToJsonNull$"},
{"l":"api/little/json/Implicits$$jsonStringToString$.html","n":"jsonStringToString","t":"given jsonStringToString: JsonInput[String]","d":"little/json/Implicits$$jsonStringToString$"},
{"l":"api/little/json/Implicits$$jsonStringToString$.html","n":"apply","t":"def apply(value: JsonValue): String","d":"little/json/Implicits$$jsonStringToString$"},
{"l":"api/little/json/Implicits$$jsonNumberToShort$.html","n":"jsonNumberToShort","t":"given jsonNumberToShort: JsonInput[Short]","d":"little/json/Implicits$$jsonNumberToShort$"},
{"l":"api/little/json/Implicits$$jsonNumberToShort$.html","n":"apply","t":"def apply(value: JsonValue): Short","d":"little/json/Implicits$$jsonNumberToShort$"},
{"l":"api/little/json/Implicits$$jsonNumberToInt$.html","n":"jsonNumberToInt","t":"given jsonNumberToInt: JsonInput[Int]","d":"little/json/Implicits$$jsonNumberToInt$"},
{"l":"api/little/json/Implicits$$jsonNumberToInt$.html","n":"apply","t":"def apply(value: JsonValue): Int","d":"little/json/Implicits$$jsonNumberToInt$"},
{"l":"api/little/json/Implicits$$jsonNumberToLong$.html","n":"jsonNumberToLong","t":"given jsonNumberToLong: JsonInput[Long]","d":"little/json/Implicits$$jsonNumberToLong$"},
{"l":"api/little/json/Implicits$$jsonNumberToLong$.html","n":"apply","t":"def apply(value: JsonValue): Long","d":"little/json/Implicits$$jsonNumberToLong$"},
{"l":"api/little/json/Implicits$$jsonNumberToFloat$.html","n":"jsonNumberToFloat","t":"given jsonNumberToFloat: JsonInput[Float]","d":"little/json/Implicits$$jsonNumberToFloat$"},
{"l":"api/little/json/Implicits$$jsonNumberToFloat$.html","n":"apply","t":"def apply(value: JsonValue): Float","d":"little/json/Implicits$$jsonNumberToFloat$"},
{"l":"api/little/json/Implicits$$jsonNumberToDouble$.html","n":"jsonNumberToDouble","t":"given jsonNumberToDouble: JsonInput[Double]","d":"little/json/Implicits$$jsonNumberToDouble$"},
{"l":"api/little/json/Implicits$$jsonNumberToDouble$.html","n":"apply","t":"def apply(value: JsonValue): Double","d":"little/json/Implicits$$jsonNumberToDouble$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigInt$.html","n":"jsonNumberToBigInt","t":"given jsonNumberToBigInt: JsonInput[BigInt]","d":"little/json/Implicits$$jsonNumberToBigInt$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigInt$.html","n":"apply","t":"def apply(value: JsonValue): BigInt","d":"little/json/Implicits$$jsonNumberToBigInt$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigDecimal$.html","n":"jsonNumberToBigDecimal","t":"given jsonNumberToBigDecimal: JsonInput[BigDecimal]","d":"little/json/Implicits$$jsonNumberToBigDecimal$"},
{"l":"api/little/json/Implicits$$jsonNumberToBigDecimal$.html","n":"apply","t":"def apply(value: JsonValue): BigDecimal","d":"little/json/Implicits$$jsonNumberToBigDecimal$"},
{"l":"api/little/json/Implicits$$jsonNumberToBoolean$.html","n":"jsonNumberToBoolean","t":"given jsonNumberToBoolean: JsonInput[Boolean]","d":"little/json/Implicits$$jsonNumberToBoolean$"},
{"l":"api/little/json/Implicits$$jsonNumberToBoolean$.html","n":"apply","t":"def apply(value: JsonValue): Boolean","d":"little/json/Implicits$$jsonNumberToBoolean$"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"jsonValueToCollection","t":"given jsonValueToCollection[T, M[T]](using val convert: JsonInput[T])(using val factory: Factory[T, M[T]]): JsonInput[M[T]]","d":"little/json/Implicits$$jsonValueToCollection"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$$jsonValueToCollection"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"factory","t":"val factory: Factory[T, M[T]]","d":"little/json/Implicits$$jsonValueToCollection"},
{"l":"api/little/json/Implicits$$jsonValueToCollection.html","n":"apply","t":"def apply(value: JsonValue): M[T]","d":"little/json/Implicits$$jsonValueToCollection"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"jsonValueToOption","t":"given jsonValueToOption[T](using val convert: JsonInput[T]): JsonInput[Option[T]]","d":"little/json/Implicits$$jsonValueToOption"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$$jsonValueToOption"},
{"l":"api/little/json/Implicits$$jsonValueToOption.html","n":"apply","t":"def apply(value: JsonValue): Option[T]","d":"little/json/Implicits$$jsonValueToOption"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"jsonValueToTry","t":"given jsonValueToTry[T](using val convert: JsonInput[T]): JsonInput[Try[T]]","d":"little/json/Implicits$$jsonValueToTry"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"convert","t":"val convert: JsonInput[T]","d":"little/json/Implicits$$jsonValueToTry"},
{"l":"api/little/json/Implicits$$jsonValueToTry.html","n":"apply","t":"def apply(value: JsonValue): Try[T]","d":"little/json/Implicits$$jsonValueToTry"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"jsonValueToEither","t":"given jsonValueToEither[A, B](using val left: JsonInput[A])(using val right: JsonInput[B]): JsonInput[Either[A, B]]","d":"little/json/Implicits$$jsonValueToEither"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"left","t":"val left: JsonInput[A]","d":"little/json/Implicits$$jsonValueToEither"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"right","t":"val right: JsonInput[B]","d":"little/json/Implicits$$jsonValueToEither"},
{"l":"api/little/json/Implicits$$jsonValueToEither.html","n":"apply","t":"def apply(value: JsonValue): Either[A, B]","d":"little/json/Implicits$$jsonValueToEither"},
{"l":"api/little/json/Implicits$$stringToJsonString$.html","n":"stringToJsonString","t":"given stringToJsonString: JsonOutput[String]","d":"little/json/Implicits$$stringToJsonString$"},
{"l":"api/little/json/Implicits$$stringToJsonString$.html","n":"apply","t":"def apply(value: String): JsonValue","d":"little/json/Implicits$$stringToJsonString$"},
{"l":"api/little/json/Implicits$$shortToJsonNumber$.html","n":"shortToJsonNumber","t":"given shortToJsonNumber: JsonOutput[Short]","d":"little/json/Implicits$$shortToJsonNumber$"},
{"l":"api/little/json/Implicits$$shortToJsonNumber$.html","n":"apply","t":"def apply(value: Short): JsonValue","d":"little/json/Implicits$$shortToJsonNumber$"},
{"l":"api/little/json/Implicits$$intToJsonNumber$.html","n":"intToJsonNumber","t":"given intToJsonNumber: JsonOutput[Int]","d":"little/json/Implicits$$intToJsonNumber$"},
{"l":"api/little/json/Implicits$$intToJsonNumber$.html","n":"apply","t":"def apply(value: Int): JsonValue","d":"little/json/Implicits$$intToJsonNumber$"},
{"l":"api/little/json/Implicits$$longToJsonNumber$.html","n":"longToJsonNumber","t":"given longToJsonNumber: JsonOutput[Long]","d":"little/json/Implicits$$longToJsonNumber$"},
{"l":"api/little/json/Implicits$$longToJsonNumber$.html","n":"apply","t":"def apply(value: Long): JsonValue","d":"little/json/Implicits$$longToJsonNumber$"},
{"l":"api/little/json/Implicits$$floatToJsonNumber$.html","n":"floatToJsonNumber","t":"given floatToJsonNumber: JsonOutput[Float]","d":"little/json/Implicits$$floatToJsonNumber$"},
{"l":"api/little/json/Implicits$$floatToJsonNumber$.html","n":"apply","t":"def apply(value: Float): JsonValue","d":"little/json/Implicits$$floatToJsonNumber$"},
{"l":"api/little/json/Implicits$$doubleToJsonNumber$.html","n":"doubleToJsonNumber","t":"given doubleToJsonNumber: JsonOutput[Double]","d":"little/json/Implicits$$doubleToJsonNumber$"},
{"l":"api/little/json/Implicits$$doubleToJsonNumber$.html","n":"apply","t":"def apply(value: Double): JsonValue","d":"little/json/Implicits$$doubleToJsonNumber$"},
{"l":"api/little/json/Implicits$$bigIntToJsonNumber$.html","n":"bigIntToJsonNumber","t":"given bigIntToJsonNumber: JsonOutput[BigInt]","d":"little/json/Implicits$$bigIntToJsonNumber$"},
{"l":"api/little/json/Implicits$$bigIntToJsonNumber$.html","n":"apply","t":"def apply(value: BigInt): JsonValue","d":"little/json/Implicits$$bigIntToJsonNumber$"},
{"l":"api/little/json/Implicits$$bigDecimalToJsonNumber$.html","n":"bigDecimalToJsonNumber","t":"given bigDecimalToJsonNumber: JsonOutput[BigDecimal]","d":"little/json/Implicits$$bigDecimalToJsonNumber$"},
{"l":"api/little/json/Implicits$$bigDecimalToJsonNumber$.html","n":"apply","t":"def apply(value: BigDecimal): JsonValue","d":"little/json/Implicits$$bigDecimalToJsonNumber$"},
{"l":"api/little/json/Implicits$$booleanToJsonBoolean$.html","n":"booleanToJsonBoolean","t":"given booleanToJsonBoolean: JsonOutput[Boolean]","d":"little/json/Implicits$$booleanToJsonBoolean$"},
{"l":"api/little/json/Implicits$$booleanToJsonBoolean$.html","n":"apply","t":"def apply(value: Boolean): JsonValue","d":"little/json/Implicits$$booleanToJsonBoolean$"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"arrayToJsonArray","t":"given arrayToJsonArray[T](using val convert: JsonOutput[T]): JsonOutput[Array[T]]","d":"little/json/Implicits$$arrayToJsonArray"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$arrayToJsonArray"},
{"l":"api/little/json/Implicits$$arrayToJsonArray.html","n":"apply","t":"def apply(value: Array[T]): JsonValue","d":"little/json/Implicits$$arrayToJsonArray"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"iterableToJsonArray","t":"given iterableToJsonArray[T, M <: ([T] =>> Iterable[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$$iterableToJsonArray"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$iterableToJsonArray"},
{"l":"api/little/json/Implicits$$iterableToJsonArray.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$$iterableToJsonArray"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"optionToJsonValue","t":"given optionToJsonValue[T, M <: ([T] =>> Option[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$$optionToJsonValue"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$optionToJsonValue"},
{"l":"api/little/json/Implicits$$optionToJsonValue.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$$optionToJsonValue"},
{"l":"api/little/json/Implicits$$noneToJsonValue$.html","n":"noneToJsonValue","t":"given noneToJsonValue: JsonOutput[None]","d":"little/json/Implicits$$noneToJsonValue$"},
{"l":"api/little/json/Implicits$$noneToJsonValue$.html","n":"apply","t":"def apply(value: None): JsonValue","d":"little/json/Implicits$$noneToJsonValue$"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"tryToJsonValue","t":"given tryToJsonValue[T, M <: ([T] =>> Try[T])](using val convert: JsonOutput[T]): JsonOutput[M[T]]","d":"little/json/Implicits$$tryToJsonValue"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$tryToJsonValue"},
{"l":"api/little/json/Implicits$$tryToJsonValue.html","n":"apply","t":"def apply(value: M[T]): JsonValue","d":"little/json/Implicits$$tryToJsonValue"},
{"l":"api/little/json/Implicits$$failureToJsonValue$.html","n":"failureToJsonValue","t":"given failureToJsonValue: JsonOutput[Failure[_]]","d":"little/json/Implicits$$failureToJsonValue$"},
{"l":"api/little/json/Implicits$$failureToJsonValue$.html","n":"apply","t":"def apply(value: Failure[_]): JsonValue","d":"little/json/Implicits$$failureToJsonValue$"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"eitherToJsonValue","t":"given eitherToJsonValue[A, B, M <: ([A, B] =>> Either[A, B])](using val left: JsonOutput[A])(using val right: JsonOutput[B]): JsonOutput[M[A, B]]","d":"little/json/Implicits$$eitherToJsonValue"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"left","t":"val left: JsonOutput[A]","d":"little/json/Implicits$$eitherToJsonValue"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"right","t":"val right: JsonOutput[B]","d":"little/json/Implicits$$eitherToJsonValue"},
{"l":"api/little/json/Implicits$$eitherToJsonValue.html","n":"apply","t":"def apply(value: M[A, B]): JsonValue","d":"little/json/Implicits$$eitherToJsonValue"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"rightToJsonValue","t":"given rightToJsonValue[T](using val convert: JsonOutput[T]): JsonOutput[Right[_, T]]","d":"little/json/Implicits$$rightToJsonValue"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$rightToJsonValue"},
{"l":"api/little/json/Implicits$$rightToJsonValue.html","n":"apply","t":"def apply(value: Right[_, T]): JsonValue","d":"little/json/Implicits$$rightToJsonValue"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"leftToJsonValue","t":"given leftToJsonValue[T](using val convert: JsonOutput[T]): JsonOutput[Left[T, _]]","d":"little/json/Implicits$$leftToJsonValue"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$leftToJsonValue"},
{"l":"api/little/json/Implicits$$leftToJsonValue.html","n":"apply","t":"def apply(value: Left[T, _]): JsonValue","d":"little/json/Implicits$$leftToJsonValue"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"tupleToJsonField","t":"given tupleToJsonField[T](using val convert: JsonOutput[T]): Conversion[(String, T), (String, JsonValue)]","d":"little/json/Implicits$$tupleToJsonField"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"convert","t":"val convert: JsonOutput[T]","d":"little/json/Implicits$$tupleToJsonField"},
{"l":"api/little/json/Implicits$$tupleToJsonField.html","n":"apply","t":"def apply(value: (String, T)): (String, JsonValue)","d":"little/json/Implicits$$tupleToJsonField"},
{"l":"api/little/json/Json$.html","n":"Json","t":"object Json","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"obj","t":"def obj(fields: (String, JsonValue)*): JsonObject","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"arr","t":"def arr(values: JsonValue*): JsonArray","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(text: String): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(bytes: Array[Byte]): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(input: Reader): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(input: InputStream): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(input: File): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"parse","t":"def parse(input: Path): JsonStructure","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"toPrettyPrint","t":"def toPrettyPrint(json: JsonStructure): String","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"toPrettyPrint","t":"def toPrettyPrint(json: JsonStructure, indent: String): String","d":"little/json/Json$"},
{"l":"api/little/json/Json$.html","n":"toJson","t":"def toJson[T](value: T)(using convert: JsonOutput[T]): JsonValue","d":"little/json/Json$"},
{"l":"api/little/json/JsonArray.html","n":"JsonArray","t":"trait JsonArray extends JsonStructure","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"values","t":"def values: Seq[JsonValue]","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"apply","t":"def apply(index: Int): JsonValue","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonObject","t":"def getJsonObject(index: Int): JsonObject","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonArray","t":"def getJsonArray(index: Int): JsonArray","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonString","t":"def getJsonString(index: Int): JsonString","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonNumber","t":"def getJsonNumber(index: Int): JsonNumber","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonBoolean","t":"def getJsonBoolean(index: Int): JsonBoolean","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getJsonNull","t":"def getJsonNull(index: Int): JsonNull","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getString","t":"def getString(index: Int): String","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getShort","t":"def getShort(index: Int): Short","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getInt","t":"def getInt(index: Int): Int","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getLong","t":"def getLong(index: Int): Long","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getFloat","t":"def getFloat(index: Int): Float","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getDouble","t":"def getDouble(index: Int): Double","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getBigInt","t":"def getBigInt(index: Int): BigInt","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getBigDecimal","t":"def getBigDecimal(index: Int): BigDecimal","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"getBoolean","t":"def getBoolean(index: Int): Boolean","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"isNull","t":"def isNull(index: Int): Boolean","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"++","t":"def ++(suffix: JsonArray): JsonArray","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":"+:","t":"def +:(value: JsonValue): JsonArray","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray.html","n":":+","t":"def :+(value: JsonValue): JsonArray","d":"little/json/JsonArray"},
{"l":"api/little/json/JsonArray$.html","n":"JsonArray","t":"object JsonArray","d":"little/json/JsonArray$"},
{"l":"api/little/json/JsonArray$.html","n":"empty","t":"def empty: JsonArray","d":"little/json/JsonArray$"},
{"l":"api/little/json/JsonArray$.html","n":"apply","t":"def apply(): JsonArray","d":"little/json/JsonArray$"},
{"l":"api/little/json/JsonArray$.html","n":"apply","t":"def apply(values: Seq[JsonValue]): JsonArray","d":"little/json/JsonArray$"},
{"l":"api/little/json/JsonArray$.html","n":"unapply","t":"def unapply(json: JsonArray): Option[Seq[JsonValue]]","d":"little/json/JsonArray$"},
{"l":"api/little/json/JsonArrayBuilder.html","n":"JsonArrayBuilder","t":"class JsonArrayBuilder","d":"little/json/JsonArrayBuilder"},
{"l":"api/little/json/JsonArrayBuilder.html","n":"add","t":"def add(value: JsonValue): JsonArrayBuilder","d":"little/json/JsonArrayBuilder"},
{"l":"api/little/json/JsonArrayBuilder.html","n":"addNull","t":"def addNull(): JsonArrayBuilder","d":"little/json/JsonArrayBuilder"},
{"l":"api/little/json/JsonArrayBuilder.html","n":"build","t":"def build(): JsonArray","d":"little/json/JsonArrayBuilder"},
{"l":"api/little/json/JsonBoolean.html","n":"JsonBoolean","t":"trait JsonBoolean extends JsonValue","d":"little/json/JsonBoolean"},
{"l":"api/little/json/JsonBoolean.html","n":"value","t":"def value: Boolean","d":"little/json/JsonBoolean"},
{"l":"api/little/json/JsonBoolean$.html","n":"JsonBoolean","t":"object JsonBoolean","d":"little/json/JsonBoolean$"},
{"l":"api/little/json/JsonBoolean$.html","n":"apply","t":"def apply(value: Boolean): JsonBoolean","d":"little/json/JsonBoolean$"},
{"l":"api/little/json/JsonBoolean$.html","n":"unapply","t":"def unapply(json: JsonBoolean): Option[Boolean]","d":"little/json/JsonBoolean$"},
{"l":"api/little/json/JsonException.html","n":"JsonException","t":"class JsonException(message: String, cause: Throwable) extends RuntimeException","d":"little/json/JsonException"},
{"l":"api/little/json/JsonException.html","n":"this","t":"def this()","d":"little/json/JsonException"},
{"l":"api/little/json/JsonException.html","n":"this","t":"def this(message: String)","d":"little/json/JsonException"},
{"l":"api/little/json/JsonException.html","n":"this","t":"def this(cause: Throwable)","d":"little/json/JsonException"},
{"l":"api/little/json/JsonFalse$.html","n":"JsonFalse","t":"object JsonFalse extends JsonBoolean","d":"little/json/JsonFalse$"},
{"l":"api/little/json/JsonFalse$.html","n":"value","t":"val value: Boolean","d":"little/json/JsonFalse$"},
{"l":"api/little/json/JsonFalse$.html","n":"toString","t":"val toString: String","d":"little/json/JsonFalse$"},
{"l":"api/little/json/JsonGenerator.html","n":"JsonGenerator","t":"trait JsonGenerator extends AutoCloseable","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeStartObject","t":"def writeStartObject(name: String): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeStartArray","t":"def writeStartArray(name: String): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeStartObject","t":"def writeStartObject(): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeStartArray","t":"def writeStartArray(): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeEnd","t":"def writeEnd(): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"write","t":"def write(name: String, value: JsonValue): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeNull","t":"def writeNull(name: String): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"write","t":"def write(value: JsonValue): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"writeNull","t":"def writeNull(): JsonGenerator","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"flush","t":"def flush(): Unit","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator.html","n":"close","t":"def close(): Unit","d":"little/json/JsonGenerator"},
{"l":"api/little/json/JsonGenerator$.html","n":"JsonGenerator","t":"object JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Writer, indent: String): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Writer): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: OutputStream, indent: String): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: OutputStream): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: File, indent: String): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: File): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Path, indent: String): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGenerator$.html","n":"apply","t":"def apply(output: Path): JsonGenerator","d":"little/json/JsonGenerator$"},
{"l":"api/little/json/JsonGeneratorError.html","n":"JsonGeneratorError","t":"class JsonGeneratorError(message: String) extends JsonException","d":"little/json/JsonGeneratorError"},
{"l":"api/little/json/JsonInput.html","n":"JsonInput","t":"trait JsonInput[T] extends Conversion[JsonValue, T]","d":"little/json/JsonInput"},
{"l":"api/little/json/JsonInput.html","n":"apply","t":"def apply(value: JsonValue): T","d":"little/json/JsonInput"},
{"l":"api/little/json/JsonNull.html","n":"JsonNull","t":"trait JsonNull extends JsonValue","d":"little/json/JsonNull"},
{"l":"api/little/json/JsonNull$.html","n":"JsonNull","t":"object JsonNull extends JsonNull","d":"little/json/JsonNull$"},
{"l":"api/little/json/JsonNull$.html","n":"toString","t":"val toString: String","d":"little/json/JsonNull$"},
{"l":"api/little/json/JsonNumber.html","n":"JsonNumber","t":"trait JsonNumber extends JsonValue","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"shortValue","t":"def shortValue: Short","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"intValue","t":"def intValue: Int","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"longValue","t":"def longValue: Long","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"floatValue","t":"def floatValue: Float","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"doubleValue","t":"def doubleValue: Double","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"bigIntValue","t":"def bigIntValue: BigInt","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber.html","n":"bigDecimalValue","t":"def bigDecimalValue: BigDecimal","d":"little/json/JsonNumber"},
{"l":"api/little/json/JsonNumber$.html","n":"JsonNumber","t":"object JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: String): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: Int): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: Long): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: Double): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: BigInt): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"apply","t":"def apply(value: BigDecimal): JsonNumber","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonNumber$.html","n":"unapply","t":"def unapply(json: JsonNumber): Option[BigDecimal]","d":"little/json/JsonNumber$"},
{"l":"api/little/json/JsonObject.html","n":"JsonObject","t":"trait JsonObject extends JsonStructure","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"names","t":"def names: Seq[String]","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"fields","t":"def fields: Map[String, JsonValue]","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"apply","t":"def apply(name: String): JsonValue","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"get","t":"def get(name: String): Option[JsonValue]","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getOrElse","t":"def getOrElse[T](name: String, default: => T)(using JsonInput[T]): T","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonObject","t":"def getJsonObject(name: String): JsonObject","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonArray","t":"def getJsonArray(name: String): JsonArray","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonString","t":"def getJsonString(name: String): JsonString","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonNumber","t":"def getJsonNumber(name: String): JsonNumber","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonBoolean","t":"def getJsonBoolean(name: String): JsonBoolean","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getJsonNull","t":"def getJsonNull(name: String): JsonNull","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getString","t":"def getString(name: String): String","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getShort","t":"def getShort(name: String): Short","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getInt","t":"def getInt(name: String): Int","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getLong","t":"def getLong(name: String): Long","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getFloat","t":"def getFloat(name: String): Float","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getDouble","t":"def getDouble(name: String): Double","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getBigInt","t":"def getBigInt(name: String): BigInt","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getBigDecimal","t":"def getBigDecimal(name: String): BigDecimal","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"getBoolean","t":"def getBoolean(name: String): Boolean","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"isNull","t":"def isNull(name: String): Boolean","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"map","t":"def map[T](name: String)(using JsonInput[T]): Option[T]","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"++","t":"def ++(other: JsonObject): JsonObject","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"+","t":"def +(field: (String, JsonValue)): JsonObject","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject.html","n":"-","t":"def -(name: String): JsonObject","d":"little/json/JsonObject"},
{"l":"api/little/json/JsonObject$.html","n":"JsonObject","t":"object JsonObject","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObject$.html","n":"empty","t":"def empty: JsonObject","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObject$.html","n":"apply","t":"def apply(): JsonObject","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObject$.html","n":"apply","t":"def apply(fields: Map[String, JsonValue]): JsonObject","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObject$.html","n":"apply","t":"def apply(fields: Seq[(String, JsonValue)]): JsonObject","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObject$.html","n":"unapply","t":"def unapply(json: JsonObject): Option[Map[String, JsonValue]]","d":"little/json/JsonObject$"},
{"l":"api/little/json/JsonObjectBuilder.html","n":"JsonObjectBuilder","t":"class JsonObjectBuilder","d":"little/json/JsonObjectBuilder"},
{"l":"api/little/json/JsonObjectBuilder.html","n":"add","t":"def add(name: String, value: JsonValue): JsonObjectBuilder","d":"little/json/JsonObjectBuilder"},
{"l":"api/little/json/JsonObjectBuilder.html","n":"addNull","t":"def addNull(name: String): JsonObjectBuilder","d":"little/json/JsonObjectBuilder"},
{"l":"api/little/json/JsonObjectBuilder.html","n":"build","t":"def build(): JsonObject","d":"little/json/JsonObjectBuilder"},
{"l":"api/little/json/JsonOutput.html","n":"JsonOutput","t":"trait JsonOutput[T] extends Conversion[T, JsonValue]","d":"little/json/JsonOutput"},
{"l":"api/little/json/JsonOutput.html","n":"apply","t":"def apply(value: T): JsonValue","d":"little/json/JsonOutput"},
{"l":"api/little/json/JsonParser.html","n":"JsonParser","t":"trait JsonParser extends Iterator[Event] with AutoCloseable","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser.html","n":"hasNext","t":"def hasNext: Boolean","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser.html","n":"next","t":"def next(): Event","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser.html","n":"getObject","t":"def getObject(): JsonObject","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser.html","n":"getArray","t":"def getArray(): JsonArray","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser.html","n":"close","t":"def close(): Unit","d":"little/json/JsonParser"},
{"l":"api/little/json/JsonParser$.html","n":"JsonParser","t":"object JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(input: Reader): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(text: String): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(bytes: Array[Byte]): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(input: InputStream): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(input: File): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$.html","n":"apply","t":"def apply(input: Path): JsonParser","d":"little/json/JsonParser$"},
{"l":"api/little/json/JsonParser$$Event.html","n":"Event","t":"enum Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event$$FieldName.html","n":"FieldName","t":"case FieldName(get: String) extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event$$Value.html","n":"Value","t":"case Value(get: JsonValue) extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event.html","n":"StartObject","t":"case StartObject extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event.html","n":"StartArray","t":"case StartArray extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event.html","n":"EndObject","t":"case EndObject extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event.html","n":"EndArray","t":"case EndArray extends Event","d":"little/json/JsonParser$$Event"},
{"l":"api/little/json/JsonParser$$Event$$FieldName.html","n":"FieldName","t":"case FieldName(get: String) extends Event","d":"little/json/JsonParser$$Event$$FieldName"},
{"l":"api/little/json/JsonParser$$Event$$Value.html","n":"Value","t":"case Value(get: JsonValue) extends Event","d":"little/json/JsonParser$$Event$$Value"},
{"l":"api/little/json/JsonParserError.html","n":"JsonParserError","t":"class JsonParserError(message: String, offset: Long) extends JsonException","d":"little/json/JsonParserError"},
{"l":"api/little/json/JsonReader.html","n":"JsonReader","t":"trait JsonReader extends AutoCloseable","d":"little/json/JsonReader"},
{"l":"api/little/json/JsonReader.html","n":"read","t":"def read(): JsonStructure","d":"little/json/JsonReader"},
{"l":"api/little/json/JsonReader.html","n":"close","t":"def close(): Unit","d":"little/json/JsonReader"},
{"l":"api/little/json/JsonReader$.html","n":"JsonReader","t":"object JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(text: String): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(bytes: Array[Byte]): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(input: Reader): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(input: InputStream): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(input: File): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonReader$.html","n":"apply","t":"def apply(input: Path): JsonReader","d":"little/json/JsonReader$"},
{"l":"api/little/json/JsonString.html","n":"JsonString","t":"trait JsonString extends JsonValue","d":"little/json/JsonString"},
{"l":"api/little/json/JsonString.html","n":"value","t":"def value: String","d":"little/json/JsonString"},
{"l":"api/little/json/JsonString$.html","n":"JsonString","t":"object JsonString","d":"little/json/JsonString$"},
{"l":"api/little/json/JsonString$.html","n":"apply","t":"def apply(value: String): JsonString","d":"little/json/JsonString$"},
{"l":"api/little/json/JsonString$.html","n":"unapply","t":"def unapply(json: JsonString): Option[String]","d":"little/json/JsonString$"},
{"l":"api/little/json/JsonStructure.html","n":"JsonStructure","t":"trait JsonStructure extends JsonValue","d":"little/json/JsonStructure"},
{"l":"api/little/json/JsonStructure.html","n":"size","t":"def size: Int","d":"little/json/JsonStructure"},
{"l":"api/little/json/JsonStructure.html","n":"isEmpty","t":"def isEmpty: Boolean","d":"little/json/JsonStructure"},
{"l":"api/little/json/JsonTrue$.html","n":"JsonTrue","t":"object JsonTrue extends JsonBoolean","d":"little/json/JsonTrue$"},
{"l":"api/little/json/JsonTrue$.html","n":"value","t":"val value: Boolean","d":"little/json/JsonTrue$"},
{"l":"api/little/json/JsonTrue$.html","n":"toString","t":"val toString: String","d":"little/json/JsonTrue$"},
{"l":"api/little/json/JsonValue.html","n":"JsonValue","t":"trait JsonValue","d":"little/json/JsonValue"},
{"l":"api/little/json/JsonValue.html","n":"as","t":"def as[T](using convert: JsonInput[T]): T","d":"little/json/JsonValue"},
{"l":"api/little/json/JsonWriter.html","n":"JsonWriter","t":"trait JsonWriter extends AutoCloseable","d":"little/json/JsonWriter"},
{"l":"api/little/json/JsonWriter.html","n":"write","t":"def write(value: JsonStructure): JsonWriter","d":"little/json/JsonWriter"},
{"l":"api/little/json/JsonWriter.html","n":"close","t":"def close(): Unit","d":"little/json/JsonWriter"},
{"l":"api/little/json/JsonWriter$.html","n":"JsonWriter","t":"object JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: Writer, indent: String): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: Writer): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: OutputStream, indent: String): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: OutputStream): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: File, indent: String): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: File): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: Path, indent: String): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/JsonWriter$.html","n":"apply","t":"def apply(output: Path): JsonWriter","d":"little/json/JsonWriter$"},
{"l":"api/little/json/rpc.html","n":"little.json.rpc","t":"package little.json.rpc","d":"little/json/rpc"},
{"l":"api/little/json/rpc/Implicits$.html","n":"Implicits","t":"object Implicits","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcError$.html","n":"jsonValueToJsonRpcError","t":"given jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcError$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcError","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$.html","n":"jsonRpcErrorToJsonValue","t":"given jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$.html","n":"apply","t":"def apply(error: JsonRpcError): JsonValue","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$.html","n":"jsonValueToJsonRpcIdentifier","t":"given jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcIdentifier","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$.html","n":"jsonRpcIdentifierToJsonValue","t":"given jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$.html","n":"apply","t":"def apply(id: JsonRpcIdentifier): JsonValue","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$.html","n":"jsonValueToJsonRpcRequest","t":"given jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcRequest","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$.html","n":"jsonRpcRequestToJsonValue","t":"given jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$.html","n":"apply","t":"def apply(request: JsonRpcRequest): JsonValue","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$.html","n":"jsonValueToJsonRpcResponse","t":"given jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcResponse","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$.html","n":"jsonRpcResponseToJsonValue","t":"given jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$.html","n":"apply","t":"def apply(response: JsonRpcResponse): JsonValue","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$.html","n":"defaultOnFailure","t":"val defaultOnFailure: PartialFunction[Throwable, JsonRpcError]","d":"little/json/rpc/Implicits$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcError$.html","n":"jsonValueToJsonRpcError","t":"given jsonValueToJsonRpcError: JsonInput[JsonRpcError]","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcError$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcError$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcError","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcError$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$.html","n":"jsonRpcErrorToJsonValue","t":"given jsonRpcErrorToJsonValue: JsonOutput[JsonRpcError]","d":"little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$.html","n":"apply","t":"def apply(error: JsonRpcError): JsonValue","d":"little/json/rpc/Implicits$$jsonRpcErrorToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$.html","n":"jsonValueToJsonRpcIdentifier","t":"given jsonValueToJsonRpcIdentifier: JsonInput[JsonRpcIdentifier]","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcIdentifier","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcIdentifier$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$.html","n":"jsonRpcIdentifierToJsonValue","t":"given jsonRpcIdentifierToJsonValue: JsonOutput[JsonRpcIdentifier]","d":"little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$.html","n":"apply","t":"def apply(id: JsonRpcIdentifier): JsonValue","d":"little/json/rpc/Implicits$$jsonRpcIdentifierToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$.html","n":"jsonValueToJsonRpcRequest","t":"given jsonValueToJsonRpcRequest: JsonInput[JsonRpcRequest]","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcRequest","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcRequest$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$.html","n":"jsonRpcRequestToJsonValue","t":"given jsonRpcRequestToJsonValue: JsonOutput[JsonRpcRequest]","d":"little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$.html","n":"apply","t":"def apply(request: JsonRpcRequest): JsonValue","d":"little/json/rpc/Implicits$$jsonRpcRequestToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$.html","n":"jsonValueToJsonRpcResponse","t":"given jsonValueToJsonRpcResponse: JsonInput[JsonRpcResponse]","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$"},
{"l":"api/little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$.html","n":"apply","t":"def apply(json: JsonValue): JsonRpcResponse","d":"little/json/rpc/Implicits$$jsonValueToJsonRpcResponse$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$.html","n":"jsonRpcResponseToJsonValue","t":"given jsonRpcResponseToJsonValue: JsonOutput[JsonRpcResponse]","d":"little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$"},
{"l":"api/little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$.html","n":"apply","t":"def apply(response: JsonRpcResponse): JsonValue","d":"little/json/rpc/Implicits$$jsonRpcResponseToJsonValue$"},
{"l":"api/little/json/rpc/InternalError.html","n":"InternalError","t":"class InternalError extends JsonRpcError","d":"little/json/rpc/InternalError"},
{"l":"api/little/json/rpc/InternalError$.html","n":"InternalError","t":"object InternalError","d":"little/json/rpc/InternalError$"},
{"l":"api/little/json/rpc/InternalError$.html","n":"apply","t":"def apply(): InternalError","d":"little/json/rpc/InternalError$"},
{"l":"api/little/json/rpc/InternalError$.html","n":"apply","t":"def apply(data: JsonValue): InternalError","d":"little/json/rpc/InternalError$"},
{"l":"api/little/json/rpc/InternalError$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InternalError","d":"little/json/rpc/InternalError$"},
{"l":"api/little/json/rpc/InternalError$.html","n":"unapply","t":"def unapply(error: InternalError): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/InternalError$"},
{"l":"api/little/json/rpc/InvalidParams.html","n":"InvalidParams","t":"class InvalidParams extends JsonRpcError","d":"little/json/rpc/InvalidParams"},
{"l":"api/little/json/rpc/InvalidParams$.html","n":"InvalidParams","t":"object InvalidParams","d":"little/json/rpc/InvalidParams$"},
{"l":"api/little/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(): InvalidParams","d":"little/json/rpc/InvalidParams$"},
{"l":"api/little/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(data: JsonValue): InvalidParams","d":"little/json/rpc/InvalidParams$"},
{"l":"api/little/json/rpc/InvalidParams$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InvalidParams","d":"little/json/rpc/InvalidParams$"},
{"l":"api/little/json/rpc/InvalidParams$.html","n":"unapply","t":"def unapply(error: InvalidParams): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/InvalidParams$"},
{"l":"api/little/json/rpc/InvalidRequest.html","n":"InvalidRequest","t":"class InvalidRequest extends JsonRpcError","d":"little/json/rpc/InvalidRequest"},
{"l":"api/little/json/rpc/InvalidRequest$.html","n":"InvalidRequest","t":"object InvalidRequest","d":"little/json/rpc/InvalidRequest$"},
{"l":"api/little/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(): InvalidRequest","d":"little/json/rpc/InvalidRequest$"},
{"l":"api/little/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(data: JsonValue): InvalidRequest","d":"little/json/rpc/InvalidRequest$"},
{"l":"api/little/json/rpc/InvalidRequest$.html","n":"apply","t":"def apply(data: Option[JsonValue]): InvalidRequest","d":"little/json/rpc/InvalidRequest$"},
{"l":"api/little/json/rpc/InvalidRequest$.html","n":"unapply","t":"def unapply(error: InvalidRequest): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/InvalidRequest$"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"JsonRpcError","t":"class JsonRpcError extends JsonException","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"code","t":"def code: Int","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"message","t":"def message: String","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"data","t":"def data: Option[JsonValue]","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isParseError","t":"def isParseError: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isInvalidRequest","t":"def isInvalidRequest: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isMethodNotFound","t":"def isMethodNotFound: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isInvalidParams","t":"def isInvalidParams: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isInternalError","t":"def isInternalError: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError.html","n":"isServerError","t":"def isServerError: Boolean","d":"little/json/rpc/JsonRpcError"},
{"l":"api/little/json/rpc/JsonRpcError$.html","n":"JsonRpcError","t":"object JsonRpcError","d":"little/json/rpc/JsonRpcError$"},
{"l":"api/little/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String): JsonRpcError","d":"little/json/rpc/JsonRpcError$"},
{"l":"api/little/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String, data: JsonValue): JsonRpcError","d":"little/json/rpc/JsonRpcError$"},
{"l":"api/little/json/rpc/JsonRpcError$.html","n":"apply","t":"def apply(code: Int, message: String, data: Option[JsonValue]): JsonRpcError","d":"little/json/rpc/JsonRpcError$"},
{"l":"api/little/json/rpc/JsonRpcError$.html","n":"unapply","t":"def unapply(error: JsonRpcError): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/JsonRpcError$"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"JsonRpcIdentifier","t":"trait JsonRpcIdentifier","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"isNull","t":"def isNull: Boolean","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"isString","t":"def isString: Boolean","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"isNumber","t":"def isNumber: Boolean","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"stringValue","t":"def stringValue: String","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier.html","n":"numberValue","t":"def numberValue: Long","d":"little/json/rpc/JsonRpcIdentifier"},
{"l":"api/little/json/rpc/JsonRpcIdentifier$.html","n":"JsonRpcIdentifier","t":"object JsonRpcIdentifier","d":"little/json/rpc/JsonRpcIdentifier$"},
{"l":"api/little/json/rpc/JsonRpcIdentifier$.html","n":"nullified","t":"def nullified: JsonRpcIdentifier","d":"little/json/rpc/JsonRpcIdentifier$"},
{"l":"api/little/json/rpc/JsonRpcIdentifier$.html","n":"apply","t":"def apply(id: String): JsonRpcIdentifier","d":"little/json/rpc/JsonRpcIdentifier$"},
{"l":"api/little/json/rpc/JsonRpcIdentifier$.html","n":"apply","t":"def apply(id: Long): JsonRpcIdentifier","d":"little/json/rpc/JsonRpcIdentifier$"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"JsonRpcMessage","t":"trait JsonRpcMessage","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"version","t":"def version: String","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"id","t":"def id: JsonRpcIdentifier","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"attributes","t":"def attributes: Map[String, Any]","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"attribute","t":"def attribute[T](name: String): T","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"getAttribute","t":"def getAttribute[T](name: String): Option[T]","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcMessage.html","n":"getAttributeOrElse","t":"def getAttributeOrElse[T](name: String, default: => T): T","d":"little/json/rpc/JsonRpcMessage"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"JsonRpcRequest","t":"trait JsonRpcRequest extends JsonRpcMessage","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"method","t":"def method: String","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"params","t":"def params: Option[JsonValue]","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"isNotification","t":"def isNotification: Boolean","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"setAttributes","t":"def setAttributes(attributes: Map[String, Any]): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"putAttribute","t":"def putAttribute(name: String, value: Any): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest.html","n":"removeAttribute","t":"def removeAttribute(name: String): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest"},
{"l":"api/little/json/rpc/JsonRpcRequest$.html","n":"JsonRpcRequest","t":"object JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest$"},
{"l":"api/little/json/rpc/JsonRpcRequest$.html","n":"builder","t":"def builder(): Builder","d":"little/json/rpc/JsonRpcRequest$"},
{"l":"api/little/json/rpc/JsonRpcRequest$.html","n":"apply","t":"def apply(version: String, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest$"},
{"l":"api/little/json/rpc/JsonRpcRequest$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, method: String, params: Option[JsonValue]): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest$"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"Builder","t":"class Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"version","t":"def version(value: String): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: JsonRpcIdentifier): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: String): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"id","t":"def id(value: Long): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"idNull","t":"def idNull(): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"idUndefined","t":"def idUndefined(): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"method","t":"def method(value: String): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"params","t":"def params(value: Option[JsonValue]): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"params","t":"def params(value: JsonValue): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"attributes","t":"def attributes(value: Map[String, Any]): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"attributes","t":"def attributes(one: (String, Any), more: (String, Any)*): Builder","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcRequest$$Builder.html","n":"build","t":"def build(): JsonRpcRequest","d":"little/json/rpc/JsonRpcRequest$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"JsonRpcResponse","t":"trait JsonRpcResponse extends JsonRpcMessage","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"isResult","t":"def isResult: Boolean","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"isError","t":"def isError: Boolean","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"result","t":"def result: JsonValue","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"error","t":"def error: JsonRpcError","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"setAttributes","t":"def setAttributes(attributes: Map[String, Any]): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"putAttribute","t":"def putAttribute(name: String, value: Any): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse.html","n":"removeAttribute","t":"def removeAttribute(name: String): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse"},
{"l":"api/little/json/rpc/JsonRpcResponse$.html","n":"JsonRpcResponse","t":"object JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse$"},
{"l":"api/little/json/rpc/JsonRpcResponse$.html","n":"builder","t":"def builder(): Builder","d":"little/json/rpc/JsonRpcResponse$"},
{"l":"api/little/json/rpc/JsonRpcResponse$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, result: JsonValue): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse$"},
{"l":"api/little/json/rpc/JsonRpcResponse$.html","n":"apply","t":"def apply(version: String, id: JsonRpcIdentifier, error: JsonRpcError): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse$"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"Builder","t":"class Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"version","t":"def version(value: String): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: JsonRpcIdentifier): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: String): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"id","t":"def id(value: Long): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"idNull","t":"def idNull(): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"tryResult","t":"def tryResult(value: => JsonValue)(using onFailure: PartialFunction[Throwable, JsonRpcError]): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"resultOrError","t":"def resultOrError(value: JsonValue | JsonRpcError): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"result","t":"def result(value: JsonValue): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(value: JsonRpcError): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(code: Int, message: String, data: Option[JsonValue]): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"error","t":"def error(code: Int, message: String, data: JsonValue): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"attributes","t":"def attributes(value: Map[String, Any]): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"attributes","t":"def attributes(one: (String, Any), more: (String, Any)*): Builder","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/JsonRpcResponse$$Builder.html","n":"build","t":"def build(): JsonRpcResponse","d":"little/json/rpc/JsonRpcResponse$$Builder"},
{"l":"api/little/json/rpc/MethodNotFound.html","n":"MethodNotFound","t":"class MethodNotFound extends JsonRpcError","d":"little/json/rpc/MethodNotFound"},
{"l":"api/little/json/rpc/MethodNotFound$.html","n":"MethodNotFound","t":"object MethodNotFound","d":"little/json/rpc/MethodNotFound$"},
{"l":"api/little/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(): MethodNotFound","d":"little/json/rpc/MethodNotFound$"},
{"l":"api/little/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(data: JsonValue): MethodNotFound","d":"little/json/rpc/MethodNotFound$"},
{"l":"api/little/json/rpc/MethodNotFound$.html","n":"apply","t":"def apply(data: Option[JsonValue]): MethodNotFound","d":"little/json/rpc/MethodNotFound$"},
{"l":"api/little/json/rpc/MethodNotFound$.html","n":"unapply","t":"def unapply(error: MethodNotFound): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/MethodNotFound$"},
{"l":"api/little/json/rpc/ParseError.html","n":"ParseError","t":"class ParseError extends JsonRpcError","d":"little/json/rpc/ParseError"},
{"l":"api/little/json/rpc/ParseError$.html","n":"ParseError","t":"object ParseError","d":"little/json/rpc/ParseError$"},
{"l":"api/little/json/rpc/ParseError$.html","n":"apply","t":"def apply(): ParseError","d":"little/json/rpc/ParseError$"},
{"l":"api/little/json/rpc/ParseError$.html","n":"apply","t":"def apply(data: JsonValue): ParseError","d":"little/json/rpc/ParseError$"},
{"l":"api/little/json/rpc/ParseError$.html","n":"apply","t":"def apply(data: Option[JsonValue]): ParseError","d":"little/json/rpc/ParseError$"},
{"l":"api/little/json/rpc/ParseError$.html","n":"unapply","t":"def unapply(error: ParseError): Option[(Int, String, Option[JsonValue])]","d":"little/json/rpc/ParseError$"},
{"l":"api/index.html","n":"API","t":" API","d":"api"}];